Cleanup (untested)

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -34,6 +34,9 @@ cdf(){
     fi
 }
 
+################################################################################
+# 
+################################################################################
 path_is_relative() {
     if ! [[ "$1" == /* ]] ; then
         return 0
@@ -42,6 +45,9 @@ path_is_relative() {
     fi
 }
 
+################################################################################
+# 
+################################################################################
 cdl () {
     link=$1
 
@@ -61,6 +67,9 @@ cdl () {
     cd $dir
 }
 
+################################################################################
+# 
+################################################################################
 cdw (){
     target=$(which $1)
     cd $(dirname $target)
@@ -117,24 +126,27 @@ p_valgrind(){
 # Remove accents from a file in-place (note, only the accented characters that
 # would show up in the French language).
 ################################################################################
-accents="âàäêèëéîïôöûùüÿçÂÀÄÊÈËÉÎÏÔÖÛÙÜŸÇ¨"
+   accents="âàäêèëéîïôöûùüÿçÂÀÄÊÈËÉÎÏÔÖÛÙÜŸÇ¨"
 no_accents="aaaeeeeiioouuuycAAAEEEEIIOOUUUYC "
 fremove-accents () {
-file=$1
-if [ -z $file ] ; then
-    echo "fremove-accents error: no file specified"
-    return
-fi
+	file=$1
+	if [ -z $file ] ; then
+	    echo "fremove-accents error: no file specified"
+	    return false
+	fi
 
-if ! [ -e $file -o -L $file ] ; then
-    echo "fremove-accents error: file $file doesn't exist"
-    return
-fi
+	if ! [ -e $file -o -L $file ] ; then
+	    echo "fremove-accents error: file $file doesn't exist"
+	    return false
+	fi
 
-cp $file $file.bak
-tr "$accents" "$no_accents" < $file > $file.removed_accents
+	cp $file $file.bak
+	tr "$accents" "$no_accents" < $file > $file.removed_accents
 }
 
+################################################################################
+# 
+################################################################################
 git_pwd() {
     if [[ $(git rev-parse --is-inside-work-tree 2>/dev/null) == true ]] ; then
         repo_dir=$(git rev-parse --show-toplevel 2>/dev/null)
@@ -153,6 +165,10 @@ at_cmc() {
     local username=$(whoami)
     [ $username = afsmpca ] || [ $username = afsmphc ]
 }
+
+################################################################################
+# 
+################################################################################
 cmc_network(){
     if [ -e ~/.network_is_ec ] ; then
         echo "ec"
@@ -161,6 +177,9 @@ cmc_network(){
     fi
 }
 
+################################################################################
+# 
+################################################################################
 at_poly() {
     if [ $(whoami) = phcarb ] ; then
         true
@@ -177,6 +196,9 @@ vimw() {
     vim $filepath $@
 }
 
+################################################################################
+# 
+################################################################################
 longest_common_prefix() {
     # ref https://stackoverflow.com/a/32116308/5795941
     lines="$1"
@@ -184,6 +206,9 @@ longest_common_prefix() {
     echo "$prefix" | tail -1
 }
 
+################################################################################
+# 
+################################################################################
 common_dir() {
     lines=$1
     common_text="$(longest_common_prefix "$lines")"
@@ -195,6 +220,9 @@ common_dir() {
     echo $common_dir
 }
 
+################################################################################
+# 
+################################################################################
 vimf() {
     query=$1; shift
     results="$(find . -name "$query")"
@@ -222,6 +250,9 @@ vimf() {
     fi
 }
 
+################################################################################
+# 
+################################################################################
 vimff() {
    vim $(fuzzyfind "$1")
 }
@@ -242,10 +273,17 @@ function profile() {
     cd $old_pwd
 }
 
+################################################################################
+# 
+################################################################################
 fuzzyfind() {
     search_string="$(echo $1 | sed 's/\(.\)/\*\1/g')*"
     find ./* -name "$search_string"
 }
+
+################################################################################
+# 
+################################################################################
 normal_mode() {
    unset CDPATH
 	set +o vi
@@ -253,6 +291,9 @@ normal_mode() {
    exec bash
 }
 
+################################################################################
+# 
+################################################################################
 phil_mode(){
    rm ~/.normal_mode
    if which zsh 2>/dev/null ; then
@@ -262,6 +303,9 @@ phil_mode(){
    fi
 }
 
+################################################################################
+# 
+################################################################################
 gitignore() {
    # The name giti comes from tab completion:
    # If you're in your repo's root, you have to type up to the second i for the
@@ -278,22 +322,37 @@ gitignore() {
    git diff --staged $giti
 }
 
+################################################################################
+# 
+################################################################################
 pycharm(){
    nohup pycharm $@ >/dev/null 2>&1 &
 }
 
+################################################################################
+# 
+################################################################################
 org(){
     emacs -nw ~/Documents/Notes/Notes_BUCKET/Notes_MAIN.org
 }
 
+################################################################################
+# 
+################################################################################
 org-new(){
     emacs -nw ~/Documents/Notes/Notes_BUCKET/__NEW__.org
 }
 
+################################################################################
+# 
+################################################################################
 echolist(){
     echo $1 | tr ':' '\n'
 }
 
+################################################################################
+# 
+################################################################################
 cmc_check_git(){
     local gv=$(git --version | cut -d ' ' -f 3)
     local major=$(cut -d '.' -f 1 <<< $gv)
@@ -306,6 +365,9 @@ cmc_check_git(){
     fi
 }
 
+################################################################################
+# 
+################################################################################
 git_stoneage_message(){
     local gv=$1
     echo "$(tput setab 1)$(tput setaf 15)You are using a version of git ($gv) from the stone age$(tput sgr 0)"
@@ -313,6 +375,9 @@ git_stoneage_message(){
     echo "make sure you do the same for gitk"
 }
 
+################################################################################
+# 
+################################################################################
 git_unsupported_message(){
     local gv=$1
     echo "$(tput setab 11)You are using a version of git ($gv) that is no longer supported$(tput sgr 0)"
