So many updates

diff --git a/cmc_home/dot-profile b/cmc_home/dot-profile
--- a/cmc_home/dot-profile
+++ b/cmc_home/dot-profile
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 p.error(){
-    printf "${FUNCNAME[1]}: \033[1;31mERROR\033[0m: $*\n"
+    printf "${FUNCNAME[1]}: \033[1;31mERROR\033[0m: $*\n" >&2
 }
 
 #
@@ -23,7 +23,8 @@ function p.profile.main(){
     export EDITOR=/usr/bin/vim
     PATH+=":$HOME/tools/go1.19.linux-amd64/bin"
     PATH+=":$HOME/tools/node-v16.13.1-linux-x64/bin"
-    PATH+=":$HOME/tools/rust0.69.0-x86_64-unknown-linux-gnu/bin"
+    # PATH+=":$HOME/tools/rust-1.69.0-x86_64-unknown-linux-gnu/bin"
+    PATH+=":/home/phc001/tools/rust-1.68.0-x86_64-unknown-linux-gnu/install-dir/bin"
     . ssmuse-sh -x /fs/ssm/hpco/exp/ssm/ssm-12.0-beta1 \
                 -x /fs/ssm/hpco/exp/ssmuse/ssmuse-1.13-beta2
     if [[ "$-" == *i* ]] ; then
@@ -38,27 +39,17 @@ function p.profile.main_interactive(){
     # unset command_not_found_handle
     export PYTHONSTARTUP=~/.pyrc
     export PACK_DIR=${HOME}/.profile.d/interactive/pack
+    export MANPATH=${HOME}/fs1/share/man:${MANPATH}
 
-    # Set directories for lazy loading of bash completions
-    # See function '_completion_loader' from /usr/share/bash-completion/bash_completion.
-    # It looks in ${BASH_COMPLETION_USER_DIR}/completions and <X>/completions
-    # for each directory in the colon separated list of paths XDG_DATA_DIRS.
-    #
-    # This is the simplest way but for things like source, this lazy loading
-    # will not happen since ordenv already sets up a broken completion function
-    # for source and . and I can't do it for ssmuse-sh and r.load.dot because
-    # they are not commands but files that are sourced.
-    #
-    # Anyway, the lazy loading is a good mechanism for all the system commands
-    # since there are like a thousand of them but for my own stuff since there
-    # are about 20 of them.
-    BASH_COMPLETION_USER_DIR=${HOME}/.bash_completion.d
-    # Fun fact, I carelessly had 'XDG_DATA_DIRS=${HOME}/fs1/etc/bash-completion'
-    # and had no problems until I started trying to use VSCode.  It was crashing
-    # but not under all circumstances.  The reason for modifying XDG_DATA_DIRS
-    # initially was because I saw that the bash-completion shell library looks
-    # there to lazy load completions for commands.
-    XDG_DATA_DIRS=${XDG_DATA_DIRS:+${XDG_DATA_DIRS}:}${HOME}/fs1/etc/bash-completion
+    # See code of __load_completion from /usr/share/bash-completion/bash_completion ...
+    # It searches an array of directories that starts out as
+    # dirs=(${BASH_COMPLETION_USER_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion}/completions)
+    # Since I don't define BASH_COMPLETION_USER_DIR and XDG_DATA_HOME
+    # is also not defined, dirs=(${HOME}/.local/share/bash-completion/completions).
+    # After that it does
+    #     for dir in ${XDG_DATA_DIRS:-/usr/local/share:/usr/share};
+    #         dirs+=($dir/bash-completion/completions);
+    XDG_DATA_DIRS=${XDG_DATA_DIRS:+${XDG_DATA_DIRS}:}${HOME}/fs1/etc
     check-alert-file ~sici000/alert
     check-alert-file ~/alert
 
@@ -66,20 +57,19 @@ function p.profile.main_interactive(){
 
     source "$HOME/.ssh/ssh_functions.sh"
     # source "$HOME/.funky-prompt.sh"
-    source "$HOME/shell_lib/powerline.sh"; __next_line_mode
-    # source $HOME/A_CLASSER/git-colon-path-support.bash
+    source "$HOME/.philconfig/shell_lib/powerline.sh"; __next_line_mode 1
+    source "$HOME/.git-completion.bash"
     SOURCE_COMPLETE_EXCLUDE_EXECUTABLE=""
     SOURCE_COMPLETE_ONLY_TEXT_FILES="yes"
     GIT_CD_VERBOSE=yes
-    source $HOME/shell_lib/git-colon-path-support.bash
-    source $HOME/shell_lib/impersonate.sh
+    source $HOME/.philconfig/shell_lib/impersonate.sh
     # Append to global history after every command.
     # .funky-prompt.sh sets PROMPT_COMMAND
     # so this next line must come AFTER sourcing ~/.funky-prompt.sh
     PROMPT_COMMAND="$PROMPT_COMMAND; history -a"
     # Replaced by single files in ~/bin
-    # maybe-source "$HOME/shell_lib/gem-functions.sh"
-    maybe-source "$HOME/shell_lib/maestro-functions.sh"
+    # maybe-source "$HOME/.philconfig/shell_lib/gem-functions.sh"
+    maybe-source "$HOME/.philconfig/shell_lib/maestro-functions.sh"
 
     # _source_dir "$HOME/.bash_completion.d"
     _source_dir "$HOME/fs1/etc/bash_completion.d"
@@ -105,20 +95,26 @@ function p.profile.main_interactive(){
 
     if [[ "${PBS_ENVIRONMENT}" == PBS_INTERACTIVE ]] ; then
         printf "PBS_ENVIRONMENT detected, cd'ing to \$PBS_O_WORKDIR=${PBS_O_WORKDIR}\n" >&2
-        cd "${PBS_O_WORKDIR}" || return
+        if ! cd "${PBS_O_WORKDIR}" ; then
+            p.error "Could not CD to '$PBS_O_WORKDIR', perhaps it is not on a network filesystem"
+        fi
         echo "${PBS_JOBID}" > ~/.ssh/current_job
         echo "JOBID ${PBS_JOBID} written in ~/.ssh/current_job" >&2
     fi
 
+    fix-source-complete
     reminders
 
     # Cd
-    alias cd=__cd_or_git_cd
-    complete -o nospace -F _cd_or_git_cd cd
+    # alias cd=__cd_or_git_cd
+    # complete -o nospace -F _cd_or_git_cd cd
+    alias cd='wrap_command_colon_paths cd'
+    complete -o default -F __complete_git_colon_dirs cd
 
     # ls
     alias ls='wrap_command_colon_paths ls --color'
     complete -o default -F __complete_git_colon_paths ls
+
 
     configure_vim
 }
@@ -230,13 +226,14 @@ function _source_dir(){
     local dir="$1"
     if ! [ -d "$1" ] ; then
         # No echo so this function can be called on non-existant dirs
-        # echo "${FUNCNAME[0]} ERROR: \$1='$1' is not a directory" >&2
+        # p.error "\$1='$1' is not a directory"
         return 1
     fi
     local f
     for f in $(command env -i ls $dir) ; do
         if ! source "$dir/$f" ; then
-            echo "${FUNCNAME[0]} ERROR: sourcing '$dir/$f' returned non-zero" >&2
+            p.error "sourcing '$dir/$f' returned non-zero"
+
         fi
     done
 }
@@ -244,12 +241,12 @@ function _source_dir(){
 
 function p.dqsubi(){
     if ! [ -e "$1" ] ; then
-        echo "ERROR: File '$1' does not exist" >&2
+        p.error "File '$1' does not exist"
         return 1
     fi
 
     if ! tempfile="$(mktemp qsubi-decorated-job-XXXXXXXX.sh)" ; then
-        echo "ERROR: Could not create tempfile" >&2
+        p.error "Could not create tempfile"
         return 1
     fi
 
@@ -269,7 +266,7 @@ function p.pipeqsubi(){
     # for us using qsub -I directly, it will complain that STDIN is not a tty 
     # and refuse to do its thing.
     if ! tempfile="$(mktemp qsubi-decorated-job-XXXXXXXX.sh)" ; then
-        echo "ERROR: Could not create tempfile" >&2
+        p.error "Could not create tempfile"
         return 1
     fi
 
@@ -385,6 +382,20 @@ CMD must be a command"
     cd "$command_location" || return
 }
 
+function cddw(){
+    local cmd=$1
+    if ! which "${cmd}" 2>/dev/null ; then
+        >&2 echo -e "Usage : ${FUNCNAME[0]} CMD
+
+CMD must be a command"
+        return 1
+    fi
+    local command_location
+    command_location="$(dirname "$(which "${cmd}")")"
+    printf "\033[33mcd %s\033[0m\n" "${command_location}" >&2
+    cd "$command_location" || return
+}
+
 function cdd(){
     local filepath=$1
     if [[ -d ${filepath} ]] ; then
@@ -393,7 +404,7 @@ function cdd(){
 
     local dir
     if ! dir=$(dirname ${filepath}) ; then
-        printf "${FUNCNAME[0]}: ERROR: Could not get dirname for '${link_target}'"
+        p.error "Could not get dirname for '${link_target}'"
         return 1
     fi
 
@@ -407,13 +418,13 @@ function cddr(){
     fi
     local link_target
     if ! link_target=$(readlink ${filepath}) ; then
-        printf "${FUNCNAME[0]}: ERROR: Could not follow link '${filepath}'"
+        p.error "Could not follow link '${filepath}'"
         return 1
     fi
 
     local dir
     if ! dir=$(dirname ${link_target}) ; then
-        printf "${FUNCNAME[0]}: ERROR: Could not get dirname for '${link_target}'"
+        p.error "Could not get dirname for '${link_target}'"
         return 1
     fi
 
@@ -509,14 +520,6 @@ function p.igfind(){
     find . -iname "*$1*"
 }
 
-function p.vstm(){
-    ~/my_scripts/vscode-tmux-session.sh
-}
-
-function p.clean-vstm(){
-    rm -f ~/.vscode-tmux-sockets/*
-}
-
 function p.myprocs(){
     ps -F -u "$USER"
 }
@@ -575,6 +578,8 @@ function p.verbose-make(){
 
 
 function make(){
+    (
+    set -o pipefail
     if ! on_compute_node ; then
         local arg
         for arg in "$@" ; do
@@ -584,7 +589,8 @@ function make(){
             fi
         done
     fi
-    command make VERBOSE=${PHIL_VERBOSE_MAKE} "$@"
+    CLICOLOR_FORCE=yep command make VERBOSE=${PHIL_VERBOSE_MAKE} --no-print-directory "$@" 2>&1 | highlight.sh error "" warning "" "undefined \w*" "^make.*"
+    )
 }
 
 
@@ -642,31 +648,22 @@ function p.qsubi(){
 function vimw(){
     local cmd=$1
     if [[ -z "${cmd}" ]] ; then
-        echo "${FUNCNAME[0]}: ERROR: Please provide a command"
+        p.error "Please provide a command"
         return 1
     fi
 
     local cmd_path
     if ! cmd_path=$(which ${cmd}) ; then
-        echo "${FUNCNAME[0]}: ERROR: Command not found using which"
+        p.error "Command not found using which"
         return 1
     fi
     vim ${cmd_path}
 }
 
-function _errprint(){
-    printf "${FUNCNAME[1]}: \033[1;31mERROR\033[0m: $*\n" >&2
-}
-
-function do_error(){
-    _errprint "An error happened, oh no!"
-}
-
 function p.view_listing(){
     local compressed_listing=$1
     if ! [[ -f "${compressed_listing}" ]] ; then
-        # printf "${FUNCNAME[0]}: \033[1;31mERROR\033[0m: Listing '${compressed_listing}' does not exist\n"
-        _errprint "Listing '${compressed_listing}' does not exist"
+        p.error "Listing '${compressed_listing}' does not exist"
         return 1
     fi
     # Assume that mktemp always succeeds
@@ -674,7 +671,7 @@ function p.view_listing(){
     gunzip -c ${compressed_listing} > ${tempfile}
     vim ${tempfile}
     if ! rm ${tempfile} ; then
-        _errprint "Could not remove '${tempfile}'"
+        p.error "Could not remove '${tempfile}'"
     fi
 }
 
@@ -701,7 +698,7 @@ py3i(){
 }
 
 
-function dump-environment(){
+function dump-environment-to-tmpfile(){
     local envdump_dir=$HOME/envdumps
     mkdir -p ${envdump_dir}
     local envdump_file=$(mktemp env_dump_$(TZ=America/Toronto date +%Y-%m-%d_%H:%M:%S)_XXX.txt --tmpdir=${envdump_dir})
@@ -722,7 +719,7 @@ function reminders(){
 
 function xargso(){
     if [[ "${1}" == "" ]] ; then
-        printf "${FUNCNAME[0]}: \033[1;31mERROR\033[0m: At least one argument must be give\n"
+        p.error "At least one argument must be give"
         return 1
     fi
     if [[ "${1}" == -h ]] ; then
@@ -750,13 +747,13 @@ function x.use(){
     local pack_dir="${1}"
     shift
     if [[ -z "${1}" ]] ; then
-        echo "${FUNCNAME[1]}: ERROR: An argument must be provided"
+        p.error "An argument must be provided"
         return 1
     fi
 
     local pack_name="${1}"
     if ! [[ -f ${pack_dir}/${pack_name} ]] ; then
-        echo "${FUNCNAME[1]}: ERROR: No package named '${pack_name}' in ${pack_dir}"
+        p.error "No package named '${pack_name}' in ${pack_dir}"
         return 1
     fi
 
@@ -769,14 +766,19 @@ function x.use(){
         if [[ -z "${line}" ]] ; then
             continue
         fi
-        printf "\033[1;32m${FUNCNAME[1]}: ${line}\033[0m\n"
+        printf "\033[1m${FUNCNAME[1]}: "
+        if [[ ${line} == \#* ]] ; then
+            printf "\033[22;34m$(eval echo ${line})\033[0m\n"
+        else
+            printf "\033[1;32m$(eval echo ${line})\033[0m\n"
+        fi
         if ! eval ${line} ; then
-            printf "${FUNCNAME[1]}: \033[1;31mERROR\033[0m error on line ${i} of ${pack_dir}/${pack_name}\n"
+            p.error "error on line ${i} of ${pack_dir}/${pack_name}"
         fi
     done < ${pack_dir}/${pack_name}
     status=$?
     if [[ ${status} != 0 ]] ; then
-        echo "${FUNCNAME[1]}: ERROR: Sourcing '${pack_dir}/${pack_name}' returned an error : $?"
+        p.error "Sourcing '${pack_dir}/${pack_name}' returned an error : $?"
     fi
     return ${status}
 }
@@ -874,9 +876,28 @@ _dispatch_pack_complete(){
     esac
 }
 
-function show-vars(){
+function p.show-vars(){
     # Show environment variables and shell variables
-    declare -p
+    (
+
+        local abbrev=$'\033[1;33m...\033[0m'
+        GLUSTER_BARRIER_OPTIONS=${abbrev}
+        GLUSTER_COMMAND_TREE=${abbrev}
+        GLUSTER_FINAL_LIST=${abbrev}
+        GLUSTER_GEO_REPLICATION_OPTIONS=${abbrev}
+        GLUSTER_GEO_REPLICATION_SUBOPTIONS=${abbrev}
+        GLUSTER_PROFILE_OPTIONS=${abbrev}
+        GLUSTER_QUOTA_OPTIONS=${abbrev}
+        GLUSTER_TOP_OPTIONS=${abbrev}
+        GLUSTER_TOP_SUBOPTIONS1=${abbrev}
+        GLUSTER_TOP_SUBOPTIONS2=${abbrev}
+        GLUSTER_VOLUME_OPTIONS=${abbrev}
+        LS_COLORS=${abbrev}
+        _xspecs=([...]="...")
+        unset abbrev
+
+        declare -p
+    )
 }
 
 function show-functions(){(
@@ -896,16 +917,18 @@ function show-functions(){(
 
 ################################################################################
 # PROBLEM: If you have 'set colored-stats on' in your ~/.inputrc, readline will
-# color completion candidates according to LS_COLORS and if you have something
-# it will color anything that is not a file (program options) accordint to the
-# as 'missing files' which if you have 'mi=01;05;37;49' in your LS_COLORS is
-# bold blinking bright white on red background which is super annoying.
+# color completion candidates according to LS_COLORS.  Therefore it will color
+# anything that is not a file (program options) according to the as 'missing
+# files' which if you have 'mi=01;05;37;49' in your LS_COLORS is bold blinking
+# bright white on red background which is super annoying.
+
 # SOLUTION: Since readline parses LS_COLORS at initialization and never again
 # after that, the trick is to set 'mi=00' in LS_COLORS, then do anything that
-# causes readline to be initialized, and then set LS_COLORS back to its original
-# value.  Alternatively we could just not put anything for missing files in
-# LS_COLORS but I wanted figure out a way to have some coloring for missing
-# files
+# causes readline to be initialized, and then set LS_COLORS back to its
+# original value.  Alternatively we could just not put anything for missing
+# files in LS_COLORS but I wanted figure out a way to have some coloring for
+# missing files
+#
 # In http://git.savannah.gnu.org/cgit/bash.git/tree/lib/readline/:
 # - In parse_colors.c:300 Function _rl_parse_colors() parses LS_COLORS
 # - In readline.c:1322 Function readline_initialize_everything
@@ -927,7 +950,11 @@ set_ls_colors_for_readline_and_ls(){
     bind -f ~/.inputrc # Anything that causes initialization of readline library
 
     # Put back the 'mi' part in LS_COLORS
-    # LS_COLORS="${my_ls_colors}"
+    # We need the 'show-colored-stats' to be for BASH only in ~/.inputrc since
+    # the python interpreter will initialize readline in its process and will
+    # read LS_COLORS.  Anyway, we don't want show-colored-stats in Python so
+    # that is totally OK.
+    LS_COLORS="${my_ls_colors}"
 
     # Another option would be to have two files but ideally, you want LS_COLORS
     # for readline to be the same for everything except for the 'mi' part
@@ -941,7 +968,141 @@ p.env(){
     env -0 | sort -z | tr '\0' '\n'
 }
 
+fix-source-complete(){
+    complete -o default -o nospace -o filenames -F _DottableCompletion source .
+}
 
+fdate(){
+    date +%Y-%m-%d_%H.%M.%S
+}
+
+p.mcd(){
+    local dir=$1
+    if [[ -z ${dir} ]] ; then
+        p.error "Name required for new directory"
+        return 1
+    fi
+
+    echo "mkdir ${dir}"
+    mkdir ${dir} || return 1
+    echo "cd ${dir}"
+    cd ${dir} || return 1
+}
+
+p.cmakel(){
+    cmake "$@" | less
+}
+
+p.shame(){
+    trap 'echo "                      a commoner kicks you"' SIGINT
+    stty -echo
+    for((i=0;i<5;i++)); do
+        echo -n "shame!"
+        sleep 1
+        echo -n " ding"
+        sleep 0.5
+        echo -n " ding"
+        sleep 2
+        echo ""
+    done
+    echo "y'know, like they did to Cercei Lannister"
+    stty echo
+    trap '' SIGINT
+    exit 1
+}
+
+p.view-rev-file(){
+    case "${1}" in -h|--help)
+        printf "Show a file at a certain revision.  Convenience wrapper for 'git show <rev>:<file>'\n\n"
+        printf "\t${FUNCNAME[0]} <rev> <file> [vim-args...]\n"
+        printf "\t${FUNCNAME[0]} <rev>:<file>:<line>\n\n"
+        printf "The one argument form is meant to take the output\n"
+        printf "of a 'git grep -p <pattern> <rev>' command\n"
+        return
+        ;;
+    esac
+
+    if [[ "$1" == *:* ]] ; then
+        local rev=${1%%:*}
+        local file_line_col=${1#*:}
+        local file=${file_line_col%%:*}
+        local line_col=${file_line_col#*:}
+        local line=${line_col%%:*}
+        echo "ref=${rev}, file_line_col=${file_line_col}, file=${file}, line=${line}"
+        git show ${rev}:${file} | vim -R - -c "doautocmd BufRead ${file}" +${line}
+    elif (( $# >= 2 )) ; then
+        local rev=$1
+        local file=$2
+        shift; shift
+        local ft=${file##*.}
+        case ${file} in
+            *Makefile|*makefile) ft=make ;;
+            CMakeLists.txt) ft=cmake ;;
+        esac
+
+        git show ${rev}:${file} | vim -R - -c "doautocmd BufRead ${file}" "$@"
+    else
+        p.error "Incorrect arguments"
+        ${FUNCNAME[0]} --help
+        return 1
+    fi
+}
+
+p.log(){
+echo "${FUNCNAME[1]}(): $@" >> ~/.log.txt
+}
+source $HOME/.philconfig/shell_lib/file_complete_elsewhere.bash
+_p.view-rev-file(){
+    local cur prev words cword
+    _init_completion || return
+
+    echo "${FUNCNAME[0]}: cword = ${cword}" >> ~/.log.txt
+    if (( cword == 1 )) ; then
+        if ! complete -p git 1>/dev/null 2>/dev/null ; then
+            __load_completion git
+        fi
+        #
+        # Git completion is set with 'compopt -o nospace' and
+        # the functions add spaces to the COMPREPLY candidates
+        #
+        compopt -o nospace
+        compopt -o filenames
+        __git_complete_refs
+        if (( ${#COMPREPLY[@]} == 1 )) ; then
+            compopt +o filenames
+        fi
+    else
+        local git_repo
+        if ! git_repo=$(git rev-parse --show-toplevel 2>/dev/null) ; then
+            return
+        fi
+        file-complete-elsewhere ${git_repo}
+
+        # compopt -o nospace
+        # compopt -o filenames
+
+        # COMPREPLY=( $(cd ${git_repo} ; compgen -f -- "${cur}") )
+        # if (( ${#COMPREPLY[@]} == 1 )) ; then
+        #     only_candidate=${COMPREPLY[0]}
+        #     if [[ -f ${git_repo}/${only_candidate} ]] ; then
+        #         COMPREPLY[0]="${only_candidate} "
+        #         compopt +o filenames
+        #     elif [[ -d ${git_repo}/${only_candidate} ]] ; then
+        #         COMPREPLY[0]="${only_candidate}/"
+        #     fi
+        # fi
+    fi
+    p.log "COMPREPLY=${COMPREPLY[@]}"
+    # for c in "${COMPREPLY[@]}" ; do
+    #     p.log "COMPREPLY elem : '${c}'"
+    # done
+}
+alias nn='vim ~/nemo_xios_notes.org'
+
+complete -o bashdefault -o default -o nospace -F _p.view-rev-file p.view-rev-file
+
+
+alias git=git-enforce-rules-of-philippes
 p.profile.main
 unset -f p.profile.main
 unset -f p.profile.main_interactive
