Various additions to .profile

diff --git a/cmc_home/dot-profile b/cmc_home/dot-profile
--- a/cmc_home/dot-profile
+++ b/cmc_home/dot-profile
@@ -305,7 +305,10 @@ function p.pipeqsubi(){
 }
 
 function gitk(){
-   command gitk --all "$@" &
+    command gitk --all "$@" &
+}
+function tig(){
+    command tig --all "$@"
 }
 
 function orgman(){
@@ -368,8 +371,8 @@ function emacs-daemon(){
 }
 
 function vimf(){
-    local directory=$1
-    vim -p $(find ${directory} -type f)
+    local directory=$1; shift
+    vim -p $(find ${directory} -type f "$@")
 }
 
 
@@ -1300,12 +1303,12 @@ make(){
         subst+="s/error/\x1b[1;31m&\x1b[0m/g; "
         subst+="s/warning/\x1b[1;33m&\x1b[0m/g; "
         subst+="s/undefined reference/\x1b[1;35m&\x1b[0m/g; "
-        subst+="s/^make.*/\x1b[1;36m&\x1b[0m/g; "
+        subst+="s/^make.*/\x1b[1;36m&\x1b[0m/g;"
         # For debugging
         # echo "subst = '$subst'"
         (
             set -o pipefail
-            CLICOLOR_FORCE=yes_please command make --no-print-directory "$@" | sed --unbuffered "${subst}"
+            CLICOLOR_FORCE=yes_please command make --no-print-directory "$@" 2>&1 | sed --unbuffered "${subst}"
         )
     fi
 }
@@ -1340,6 +1343,48 @@ p.print_ps1(){
 
 p.curl-gitlab(){
     curl --header "Private-Token: $(cat ~/.ssh/gitlab-access-token)" "$@" | jq
+}
+
+p.cmake_asm(){
+    cat <<- EOF
+		If <source_dir>/<d>/CMakeLists.txt creates a target with the
+		source file <source_dir>/<d>/<d2>/file.c, then going go into
+		<build_dir>/<d> and run 'make <d2>/file.c.s to generate the
+		assembly for file.c.  The path will be printed.  It should be
+		<build_dir>/<d>/CMakeFiles/<target_name>.dir/file.c.s
+
+		Note: Some components of <d> may change names if
+		add_subdirectory(a a2) is used.  For example, if <d> = a/b/c
+		in the source dir would become <d> = a2/b/c in the build_dir
+		Multiple components can be replaced by a single component as
+		well add_subdirectory(a/b/c e) would mean that we would need
+		to go to <build_dir>/e to run 'make <d2>/file.c.s.
+	EOF
+}
+
+function ancestor_with_basename(){
+    local ancestor=$1
+    local dir=$PWD
+    while [[ "$(basename $dir)" != "${ancestor}" ]] ; do
+        if [[ "${dir}" == "/" ]] ; then
+            echo "Root reached and ancestor '${ancestor}' not found" >&2
+            return 1
+        fi
+        dir=$(dirname $dir)
+    done
+    echo $dir
+}
+
+
+function cd..(){
+    local ancestor=$1
+    local dir
+    if ! dir=$(ancestor_with_basename $ancestor) ; then
+        echo "${FUNCNAME[0]}: no ancestor with basename '$ancestor'" >&2
+        return 1
+    fi
+    printf "\033[34mcd $dir\033[0m\n"
+    cd $dir
 }
 
 p.profile.main
